# Tokyo Night — dark
set -g status-style "bg=#1a1b26,fg=#a9b1d6"
set -g status-left-style "bg=#1a1b26,fg=#bb9af7,bold"
set -g status-right-style "bg=#1a1b26,fg=#565f89"
set -g window-status-style "bg=#1a1b26,fg=#565f89"
set -g window-status-current-style "bg=#414868,fg=#7aa2f7,bold"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g status-left " 󰖲 "
set -g status-right " #S %H:%M "
