# Tokyo Night Day — light
set -g status-style "bg=#e1e2e7,fg=#3760bf"
set -g status-left-style "bg=#e1e2e7,fg=#9854f1,bold"
set -g status-right-style "bg=#e1e2e7,fg=#9699a3"
set -g window-status-style "bg=#e1e2e7,fg=#9699a3"
set -g window-status-current-style "bg=#d5d6db,fg=#3760bf,bold"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g status-left " 󰖲 "
set -g status-right " #S %H:%M "
