# Nord Light — light
set -g status-style "bg=#eceff4,fg=#2e3440"
set -g status-left-style "bg=#eceff4,fg=#5e81ac,bold"
set -g status-right-style "bg=#eceff4,fg=#d8dee9"
set -g window-status-style "bg=#eceff4,fg=#4c566a"
set -g window-status-current-style "bg=#e5e9f0,fg=#5e81ac,bold"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g status-left " 󰖲 "
set -g status-right " #S %H:%M "
