# Nord — dark
set -g status-style "bg=#2e3440,fg=#eceff4"
set -g status-left-style "bg=#2e3440,fg=#88c0d0,bold"
set -g status-right-style "bg=#2e3440,fg=#4c566a"
set -g window-status-style "bg=#2e3440,fg=#4c566a"
set -g window-status-current-style "bg=#3b4252,fg=#81a1c1,bold"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g status-left " 󰖲 "
set -g status-right " #S %H:%M "
