tmux:
  symbols:
    branch: "⎇ "
    hashprefix: ":"
    ahead: "↑"
    behind: "↓"
    staged: "● "
    conflict: "✖ "
    modified: "✚ "
    untracked: "… "
    stashed: "⚑ "
    insertions: "Σ"
    deletions: "Δ"
    clean: "✔"

  styles:
    clear: "#[fg=#{@thm_fg}]"
    state: "#[fg=#{@thm_red},bold]"
    branch: "#[fg=#{@thm_fg},bold]"
    remote: "#[fg=#{@thm_teal}]"
    divergence: "#[fg=#{@thm_fg}]"
    staged: "#[fg=#{@thm_green},bold]"
    conflict: "#[fg=#{@thm_red},bold]"
    modified: "#[fg=#{@thm_yellow},bold]"
    untracked: "#[fg=#{@thm_mauve},bold]"
    stashed: "#[fg=#{@thm_blue},bold]"
    insertions: "#[fg=#{@thm_green}]"
    deletions: "#[fg=#{@thm_red}]"
    clean: "#[fg=#{@thm_rosewater},bold]"

  layout: [branch, " ", flags]

  options:
    branch_max_len: 28
    branch_trim: right
    branch_truncate_symbol: "…"
