# Catppuccin Powerlevel10k — https://github.com/tolkonepiu/catppuccin-powerlevel10k-themes
# Flavour: zstyle ':catppuccin:p10k' (set via ~/.config/theme/manifest.toml)

() {
  local _plugin="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/catppuccin-powerlevel10k-themes/catppuccin-powerlevel10k-themes.plugin.zsh"
  local _flavour

  [[ -f $_plugin ]] || {
    echo "p10k: missing catppuccin-powerlevel10k-themes (run: git submodule update --init)" >&2
    return 1
  }

  zstyle -s ':catppuccin:p10k' flavour _flavour 2>/dev/null || _flavour=${P10K_CATPPUCCIN_FLAVOUR:-mocha}

  source "$_plugin"
  apply_catppuccin rainbow "$_flavour"

  # Layout — prior wizard: round separators, dotted 2-line prompt, no box frame.
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='·'
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=$P10K_COLOR_SURFACE1
  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
  typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'

  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B5'
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B7'
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B4'
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B6'
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B4'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B6'
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B6'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B4'
  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=

  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_ERROR=false

  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$P10K_COLOR_GREEN
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$P10K_COLOR_RED

  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=$P10K_COLOR_SURFACE0
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=$P10K_COLOR_TEXT

  # Segment accents — same Catppuccin tokens as catppuccin/tmux (@thm_mauve window #, @thm_teal gitmux)
  typeset -g POWERLEVEL9K_DIR_{BACKGROUND,ANCHOR_BACKGROUND}=$P10K_COLOR_MAUVE
  typeset -g POWERLEVEL9K_DIR_{FOREGROUND,ANCHOR_FOREGROUND,SHORTENED_FOREGROUND}=$P10K_COLOR_CRUST

  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=$P10K_COLOR_TEAL
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=$P10K_COLOR_YELLOW
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=$P10K_COLOR_PINK
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=$P10K_COLOR_MAROON
  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=$P10K_COLOR_SURFACE1
  typeset -g POWERLEVEL9K_VCS_{CLEAN,MODIFIED}_FOREGROUND=$P10K_COLOR_CRUST
  typeset -g POWERLEVEL9K_VCS_PREFIX='on '

  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=$P10K_COLOR_SURFACE1
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$P10K_COLOR_TEXT
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PREFIX='took '

  typeset -g POWERLEVEL9K_TIME_BACKGROUND=$P10K_COLOR_SURFACE0
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$P10K_COLOR_TEXT
  typeset -g POWERLEVEL9K_TIME_PREFIX='at '

  local -a _p10k_right=(${(@)POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS:#newline})
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=($_p10k_right time newline)
}
