# Rosé Pine Moon — dark
set -g status-style "bg=#232136,fg=#e0def4"
set -g status-left-style "bg=#232136,fg=#c4a7e7,bold"
set -g status-right-style "bg=#232136,fg=#6e6a86"
set -g window-status-style "bg=#232136,fg=#6e6a86"
set -g window-status-current-style "bg=#2a273f,fg=#9ccfd8,bold"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g status-left " 󰖲 "
set -g status-right " #S %H:%M "
