# Rosé Pine Dawn — light
set -g status-style "bg=#faf4ed,fg=#575279"
set -g status-left-style "bg=#faf4ed,fg=#907aa9,bold"
set -g status-right-style "bg=#faf4ed,fg=#9893a5"
set -g window-status-style "bg=#faf4ed,fg=#9893a5"
set -g window-status-current-style "bg=#f2e9e1,fg=#286983,bold"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g status-left " 󰖲 "
set -g status-right " #S %H:%M "
