# Gruvbox — dark
set -g status-style "bg=#282828,fg=#ebdbb2"
set -g status-left-style "bg=#282828,fg=#fabd2f,bold"
set -g status-right-style "bg=#282828,fg=#928374"
set -g window-status-style "bg=#282828,fg=#928374"
set -g window-status-current-style "bg=#3c3836,fg=#fe8019,bold"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g status-left " 󰖲 "
set -g status-right " #S %H:%M "
